# Generated by Django 4.2.6 on 2023-10-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_comunidado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comunidado',
            new_name='Comunicado',
        ),
    ]
