# Generated by Django 4.2.6 on 2023-10-23 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_rename_comunidado_comunicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comunicado',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='tipo',
            field=models.CharField(choices=[('S', 'Suspernsión de actividades'), ('C', 'Suspensión de clase'), ('I', 'Información')], default='I', max_length=1),
        ),
    ]
