# Generated by Django 4.2.6 on 2023-10-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0009_comunicado_usuario_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='usuario_creacion',
        ),
    ]
